"""initial_schema

Revision ID: e949930bc186
Revises: 
Create Date: 2026-06-29 23:38:17.918908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e949930bc186'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_rules', schema=None) as batch_op:
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
